import { ChangeDetectionStrategy, Component, inject, signal, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Appointment, CatalogItem, SchedulingApiService } from '../../../services/scheduling-api.service';

interface Block { id:number; locationId:number; date:string; startTime:string; endTime:string; }
@Component({selector:'app-mi-agenda',changeDetection:ChangeDetectionStrategy.OnPush,imports:[FormsModule],template:`
<section class="space-y-6"><div><p class="text-xs text-outline">Profesional</p><h1 class="text-2xl font-bold">Mi agenda asistencial</h1></div>
<form class="rounded-3xl bg-surface-container-lowest border border-outline-variant/40 p-6 grid gap-4 md:grid-cols-4" (ngSubmit)="saveBlock()"><label class="text-xs font-semibold">Sede<select class="mt-1 w-full p-2 rounded-xl" [(ngModel)]="locationId" name="location"><option [ngValue]="0">Seleccione</option>@for(l of locations();track l.id){<option [ngValue]="l.id">{{l.name}}</option>}</select></label><label class="text-xs font-semibold">Fecha<input class="mt-1 w-full p-2 rounded-xl" type="date" [(ngModel)]="date" name="date"></label><label class="text-xs font-semibold">Inicio<input class="mt-1 w-full p-2 rounded-xl" type="time" [(ngModel)]="startTime" name="start"></label><label class="text-xs font-semibold">Fin<input class="mt-1 w-full p-2 rounded-xl" type="time" [(ngModel)]="endTime" name="end"></label><button class="self-end py-2 rounded-xl bg-primary text-on-primary">{{editingId?'Guardar cambios':'Publicar bloque'}}</button>@if(editingId){<button type="button" class="py-2 rounded-xl border" (click)="cancelEdit()">Cancelar edición</button>}</form>
@if(message()){<p class="text-sm" [class.text-error]="error()">{{message()}}</p>}
<div class="rounded-3xl bg-surface-container-lowest border border-outline-variant/40 p-5"><h2 class="font-bold">Bloques publicados</h2>@for(b of blocks();track b.id){<div class="py-2 text-sm border-b border-outline-variant/20 flex justify-between gap-3"><span>{{b.date}} · {{b.startTime}}–{{b.endTime}} · sede #{{b.locationId}}</span><span class="flex gap-2"><button class="text-primary" (click)="edit(b)">Editar</button><button class="text-error" (click)="remove(b)">Eliminar</button></span></div>}@empty{<p class="text-sm text-outline mt-3">No hay bloques publicados.</p>}</div>
<div class="rounded-3xl bg-surface-container-lowest border border-outline-variant/40 p-5"><div class="flex flex-wrap justify-between gap-2"><h2 class="font-bold">Citas aprobadas</h2><button class="text-primary" (click)="loadAgenda()">Actualizar</button></div>@for(a of agenda();track a.id){<p class="py-2 text-sm border-b border-outline-variant/20">{{a.date}} · {{a.startTime}} · {{a.durationMinutes}} min · sede #{{a.locationId}} · paciente protegido</p>}@empty{<p class="text-sm text-outline mt-3">No hay citas aprobadas para la agenda.</p>}</div></section>`})
export class MiAgendaPage {private readonly api=inject(SchedulingApiService);private readonly platform=inject(PLATFORM_ID);readonly locations=signal<CatalogItem[]>([]);readonly blocks=signal<Block[]>([]);readonly agenda=signal<Appointment[]>([]);readonly message=signal('');readonly error=signal(false);locationId=0;date=new Date(Date.now()+86400000).toISOString().slice(0,10);startTime='08:00';endTime='12:00';editingId?:number;constructor(){if(isPlatformBrowser(this.platform)){this.api.locations().subscribe({next:x=>this.locations.set(x)});this.load();this.loadAgenda();}}load(){this.api.blocks().subscribe({next:x=>this.blocks.set(x),error:e=>this.show(e.status===403?'Solo PROFESSIONAL puede gestionar bloques.':'No fue posible cargar bloques.',true)});}loadAgenda(){this.api.agenda().subscribe({next:x=>this.agenda.set(x),error:()=>this.show('No fue posible cargar la agenda de citas.',true)});}saveBlock(){if(!this.locationId){this.show('Seleccione una sede.',true);return;}const body={locationId:this.locationId,date:this.date,startTime:this.startTime,endTime:this.endTime};const request=this.editingId?this.api.updateBlock(this.editingId,body):this.api.createBlock(body);request.subscribe({next:()=>{this.show(this.editingId?'Bloque actualizado.':'Bloque publicado.');this.cancelEdit();this.load();},error:e=>this.show(e.status===409?'El bloque se solapa o tiene citas comprometidas.':'No fue posible guardar el bloque.',true)});}edit(b:Block){this.editingId=b.id;this.locationId=b.locationId;this.date=b.date;this.startTime=b.startTime;this.endTime=b.endTime;}cancelEdit(){this.editingId=undefined;}remove(b:Block){if(!confirm('¿Eliminar este bloque futuro?'))return;this.api.deleteBlock(b.id).subscribe({next:()=>{this.show('Bloque eliminado.');this.load();},error:e=>this.show(e.status===409?'No se puede eliminar: tiene citas comprometidas.':'No fue posible eliminar el bloque.',true)});}private show(m:string,e=false){this.message.set(m);this.error.set(e);}}
