import { ChangeDetectionStrategy, Component, inject, signal, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { CatalogItem, SchedulingApiService } from '../../../services/scheduling-api.service';

interface Block { id:number; locationId:number; date:string; startTime:string; endTime:string; }
@Component({selector:'app-mi-agenda',changeDetection:ChangeDetectionStrategy.OnPush,imports:[FormsModule],template:`
<section class="space-y-6"><div><p class="text-xs text-outline">Profesional</p><h1 class="text-2xl font-bold">Mi disponibilidad</h1></div><form class="rounded-3xl bg-surface-container-lowest border border-outline-variant/40 p-6 grid gap-4 md:grid-cols-4" (ngSubmit)="create()"><label class="text-xs font-semibold">Sede<select class="mt-1 w-full p-2 rounded-xl" [(ngModel)]="locationId" name="location"><option [ngValue]="0">Seleccione</option>@for(l of locations();track l.id){<option [ngValue]="l.id">{{l.name}}</option>}</select></label><label class="text-xs font-semibold">Fecha<input class="mt-1 w-full p-2 rounded-xl" type="date" [(ngModel)]="date" name="date"></label><label class="text-xs font-semibold">Horario<input class="mt-1 w-full p-2 rounded-xl" type="time" [(ngModel)]="startTime" name="start"><input class="mt-1 w-full p-2 rounded-xl" type="time" [(ngModel)]="endTime" name="end"></label><button class="self-end py-2 rounded-xl bg-primary text-on-primary">Publicar bloque</button></form>@if(message()){<p class="text-sm" [class.text-error]="error()">{{message()}}</p>}<div class="rounded-3xl bg-surface-container-lowest border border-outline-variant/40 p-5"><h2 class="font-bold">Bloques publicados</h2>@for(b of blocks();track b.id){<p class="py-2 text-sm border-b border-outline-variant/20">{{b.date}} · {{b.startTime}}–{{b.endTime}} · sede #{{b.locationId}}</p>}@empty{<p class="text-sm text-outline mt-3">No hay bloques publicados.</p>}</div></section>`})
export class MiAgendaPage {private readonly api=inject(SchedulingApiService);private readonly platform=inject(PLATFORM_ID);readonly locations=signal<CatalogItem[]>([]);readonly blocks=signal<Block[]>([]);readonly message=signal('');readonly error=signal(false);locationId=0;date=new Date(Date.now()+86400000).toISOString().slice(0,10);startTime='08:00';endTime='12:00';constructor(){if(isPlatformBrowser(this.platform)){this.api.locations().subscribe({next:x=>this.locations.set(x)});this.load();}}load(){this.api.blocks().subscribe({next:x=>this.blocks.set(x as Block[]),error:e=>this.show(e.status===403?'Solo PROFESSIONAL puede gestionar bloques.':'No fue posible cargar bloques.',true)});}create(){if(!this.locationId){this.show('Seleccione una sede.',true);return;}this.api.createBlock({locationId:this.locationId,date:this.date,startTime:this.startTime,endTime:this.endTime}).subscribe({next:()=>{this.show('Bloque publicado.');this.load();},error:e=>this.show(e.status===409?'El bloque se solapa con otro.':'No fue posible publicar el bloque.',true)});}private show(m:string,e=false){this.message.set(m);this.error.set(e);}}
