import { ChangeDetectionStrategy, Component, inject, signal, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Professional, SchedulingApiService, Specialty } from '../../../services/scheduling-api.service';

@Component({ selector:'app-profesionales-catalogos', changeDetection:ChangeDetectionStrategy.OnPush, imports:[FormsModule], template:`
<section class="space-y-6"><div><p class="text-xs text-outline">Administración</p><h1 class="text-2xl font-bold">Profesionales y especialidades</h1></div>
<div class="grid gap-5 md:grid-cols-2"><form class="rounded-3xl bg-surface-container-lowest border border-outline-variant/40 p-5 space-y-3" (ngSubmit)="createSpecialty()"><h2 class="font-bold">Nueva especialidad</h2><input class="w-full p-2 rounded-xl" [(ngModel)]="specialtyName" name="specialtyName" placeholder="Nombre" required><select class="w-full p-2 rounded-xl" [(ngModel)]="duration" name="duration"><option [ngValue]="30">30 minutos</option><option [ngValue]="60">60 minutos</option></select><label class="flex gap-2 text-sm"><input type="checkbox" [(ngModel)]="requiresAdminApproval" name="requiresAdminApproval"> Requiere aprobación ADMIN</label><button class="px-4 py-2 rounded-xl bg-primary text-on-primary">Guardar</button></form>
<div class="rounded-3xl bg-surface-container-lowest border border-outline-variant/40 p-5"><h2 class="font-bold mb-3">Especialidades activas</h2>@for(s of specialties();track s.id){<p class="text-sm py-1">{{s.name}} · {{s.durationMinutes}} min</p>}@empty{<p class="text-sm text-outline">Sin datos.</p>}</div></div>
<div class="rounded-3xl bg-surface-container-lowest border border-outline-variant/40 p-5"><div class="flex justify-between"><h2 class="font-bold">Profesionales y asignaciones</h2><button class="text-primary text-sm" (click)="load()">Actualizar</button></div>@for(p of professionals();track p.id){<div class="py-3 border-b border-outline-variant/20 space-y-2"><div class="flex justify-between"><span>{{p.name}} · {{p.professionalCode}}</span><button class="px-3 py-1 rounded-lg" [class.bg-primary]="p.active" [class.text-on-primary]="p.active" (click)="toggle(p)">{{p.active?'Activo':'Inactivo'}}</button></div><div class="grid gap-2 md:grid-cols-3 text-xs"><label>Especialidades<select multiple class="w-full p-1 rounded-lg" [(ngModel)]="specialtyAssignments[p.id]" [name]="'specialties-'+p.id">@for(s of specialties();track s.id){<option [ngValue]="s.id">{{s.name}}</option>}</select></label><label>Especialidad primaria<select class="w-full p-1 rounded-lg" [(ngModel)]="primaryAssignments[p.id]" [name]="'primary-'+p.id"><option [ngValue]="undefined">Seleccione</option>@for(s of specialties();track s.id){<option [ngValue]="s.id">{{s.name}}</option>}</select></label><label>Sedes<select multiple class="w-full p-1 rounded-lg" [(ngModel)]="locationAssignments[p.id]" [name]="'locations-'+p.id">@for(l of locations();track l.id){<option [ngValue]="l.id">{{l.name}}</option>}</select></label></div><button class="text-xs px-3 py-1 rounded-lg bg-secondary text-on-secondary" (click)="saveAssignments(p.id)">Guardar asignaciones</button></div>}@empty{<p class="text-sm text-outline mt-3">No hay profesionales creados.</p>}</div>
@if(message()){<p class="text-sm" [class.text-error]="error()">{{message()}}</p>}</section>`})
export class ProfesionalesCatalogosPage { private readonly api=inject(SchedulingApiService);private readonly platform=inject(PLATFORM_ID); readonly specialties=signal<Specialty[]>([]);readonly professionals=signal<Professional[]>([]);readonly locations=signal<{id:number;name:string}[]>([]);readonly message=signal('');readonly error=signal(false);specialtyName='';duration=30;requiresAdminApproval=true;specialtyAssignments:Record<number,number[]>={};primaryAssignments:Record<number,number|undefined>={};locationAssignments:Record<number,number[]>={};constructor(){if(isPlatformBrowser(this.platform))this.load();}load(){this.api.adminSpecialties().subscribe({next:x=>this.specialties.set(x),error:()=>this.show('No fue posible cargar datos.',true)});this.api.locations().subscribe({next:x=>this.locations.set(x)});this.api.professionals().subscribe({next:x=>{this.professionals.set(x);x.forEach(p=>{this.specialtyAssignments[p.id]??=[];this.locationAssignments[p.id]??=[];});},error:()=>{}});}createSpecialty(){this.api.createSpecialty({name:this.specialtyName,durationMinutes:this.duration,requiresAdminApproval:this.requiresAdminApproval,active:true}).subscribe({next:()=>{this.specialtyName='';this.show('Especialidad creada.');this.load();},error:e=>this.show(e.status===403?'Solo ADMIN puede crear especialidades.':'No fue posible crear la especialidad.',true)});}saveAssignments(id:number){const specialties=this.specialtyAssignments[id]||[];const primary=this.primaryAssignments[id];const locations=this.locationAssignments[id]||[];if(!specialties.length||!primary||!locations.length||!specialties.includes(primary)){this.show('Asigna especialidades, primaria y al menos una sede.',true);return;}this.api.setAssignments(id,{specialtyIds:specialties,primarySpecialtyId:primary,locationIds:locations}).subscribe({next:()=>this.show('Asignaciones guardadas.'),error:()=>this.show('No fue posible guardar las asignaciones.',true)});}toggle(p:Professional){this.api.setProfessionalActive(p.id,!p.active).subscribe({next:()=>this.load(),error:()=>this.show('No fue posible actualizar el profesional.',true)});}private show(m:string,e=false){this.message.set(m);this.error.set(e);}}
