import { ChangeDetectionStrategy, Component, PLATFORM_ID, inject, signal } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { RouterLink } from '@angular/router';
import { SchedulingApiService, Appointment } from '../../../services/scheduling-api.service';
import { BadgeService } from '../../../services/badge.service';

@Component({selector:'app-paciente-inicio',changeDetection:ChangeDetectionStrategy.OnPush,imports:[RouterLink],template:`
<div class="space-y-6"><div><p class="text-xs text-outline">Portal Paciente</p><h1 class="text-2xl sm:text-3xl font-bold">Resumen de citas</h1><p class="text-sm text-outline mt-1">Información sincronizada con tus citas reales.</p></div>
<div class="rounded-3xl bg-primary text-on-primary p-6 sm:p-8"><h2 class="text-xl sm:text-2xl font-bold">¿Necesitas una nueva valoración médica?</h2><p class="text-sm opacity-80 mt-2 mb-5">Consulta horarios disponibles y solicita una nueva cita.</p><a routerLink="/paciente/buscar-disponibilidad" class="inline-flex px-5 py-3 rounded-xl bg-surface-container-lowest text-primary font-semibold text-sm">Solicitar cita médica</a></div>
@if(error()){<p class="text-error text-sm">{{error()}}</p>} @if(nextAppointment(); as next){<section class="rounded-3xl bg-surface-container-lowest p-6 border border-outline-variant/40"><div class="flex items-center justify-between gap-3 mb-4"><h2 class="font-bold">Próxima cita</h2><span class="px-3 py-1 rounded-full text-xs font-bold bg-primary-fixed">{{next.status}}</span></div><p class="font-semibold">Cita #{{next.id}}</p><p class="text-sm text-outline">{{next.date}} · {{next.startTime}} · {{next.durationMinutes}} min</p><p class="text-sm mt-1">Sede {{next.locationId}} · Profesional {{next.professionalId}} · Especialidad {{next.specialtyId}}</p>@if(next.status==='APPROVED' && isFuture(next)){<button class="mt-4 px-3 py-2 rounded-xl text-error border border-error/30 text-sm" (click)="cancel(next.id)">Cancelar cita</button>}</section>}
<section><div class="flex items-center justify-between mb-3"><h2 class="font-bold">Citas próximas y en trámite</h2><a routerLink="/paciente/mis-citas" class="text-xs text-primary font-semibold">Ver historial completo</a></div><div class="grid gap-3 md:grid-cols-2">@for(appointment of appointments();track appointment.id){<article class="rounded-2xl bg-surface-container-lowest p-4 border border-outline-variant/40"><p class="font-bold">Cita #{{appointment.id}} · {{appointment.status}}</p><p class="text-sm text-outline">{{appointment.date}} · {{appointment.startTime}} · {{appointment.durationMinutes}} min</p><p class="text-sm">Sede {{appointment.locationId}} · Profesional {{appointment.professionalId}} · Especialidad {{appointment.specialtyId}}</p></article>} @empty {<p class="text-sm text-outline">No tienes citas próximas ni solicitudes en trámite.</p>}</div></section></div>`})
export class PacienteInicioPage { private readonly api=inject(SchedulingApiService); private readonly badges=inject(BadgeService); private readonly platform=inject(PLATFORM_ID); readonly all=signal<Appointment[]>([]); readonly error=signal(''); constructor(){if(isPlatformBrowser(this.platform))this.load();} load(){this.api.mine().subscribe({next:x=>{this.all.set(x);this.badges.refresh();},error:()=>this.error.set('No fue posible cargar tus citas reales.')});} appointments(){return this.all().filter(a=>a.status==='APPROVED'||a.status==='REQUESTED');} nextAppointment(){return this.appointments().find(a=>this.isFuture(a));} isFuture(a:Appointment){return new Date(`${a.date}T${a.startTime}`)>new Date();} cancel(id:number){this.api.cancelAppointment(id).subscribe({next:()=>this.load(),error:()=>this.error.set('La cita no se puede cancelar.')});} }
