import { ChangeDetectionStrategy, Component, inject, PLATFORM_ID, signal } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { PlanItem, SchedulingApiService } from '../../services/scheduling-api.service';
import { FcvDataService } from '../../services/fcv-data.service';

@Component({
  selector: 'app-login', changeDetection: ChangeDetectionStrategy.OnPush, imports: [FormsModule],
  template: `
    <main class="min-h-screen grid place-items-center bg-surface p-6"><section class="w-full max-w-2xl grid gap-6 md:grid-cols-2">
      <div class="rounded-3xl bg-primary text-on-primary p-8"><p class="text-xs uppercase tracking-wider">FCV Citas</p><h1 class="mt-3 text-3xl font-bold">Portal de acceso clínico</h1><p class="mt-4 text-sm opacity-80">Proyecto académico con datos sintéticos. Inicie sesión o cree una cuenta USER.</p></div>
      <div class="rounded-3xl bg-surface-container-lowest p-6 border border-outline-variant/40 space-y-4">
        <div class="flex gap-4"><button class="font-bold" [class.text-primary]="mode() === 'login'" (click)="mode.set('login')">Ingresar</button><button class="font-bold" [class.text-primary]="mode() === 'register'" (click)="mode.set('register')">Registro</button><button class="font-bold" [class.text-primary]="mode() === 'recovery'" (click)="mode.set('recovery')">Recuperar contraseña</button></div>
        @if(message()){<p class="text-sm" [class.text-error]="error()">{{message()}}</p>}
        @if(mode() === 'login'){<form class="space-y-3" (ngSubmit)="login()"><input class="w-full p-3 rounded-xl bg-surface-container-low" name="email" [(ngModel)]="email" type="email" placeholder="Correo" required><input class="w-full p-3 rounded-xl bg-surface-container-low" name="password" [(ngModel)]="password" type="password" placeholder="Contraseña" required><button class="w-full p-3 rounded-xl bg-primary text-on-primary font-bold">Iniciar sesión</button></form>}
        @if(mode() === 'register'){<form class="space-y-2" (ngSubmit)="register()"><div class="grid grid-cols-2 gap-2"><input class="p-2 rounded-xl bg-surface-container-low" name="firstName" [(ngModel)]="firstName" placeholder="Nombres" required><input class="p-2 rounded-xl bg-surface-container-low" name="lastName" [(ngModel)]="lastName" placeholder="Apellidos" required></div><input class="w-full p-2 rounded-xl bg-surface-container-low" name="document" [(ngModel)]="documentNumber" placeholder="Documento" required><input class="w-full p-2 rounded-xl bg-surface-container-low" name="registerEmail" [(ngModel)]="email" type="email" placeholder="Correo" required><input class="w-full p-2 rounded-xl bg-surface-container-low" name="phone" [(ngModel)]="phone" placeholder="Teléfono" required><input class="w-full p-2 rounded-xl bg-surface-container-low" name="registerPassword" [(ngModel)]="password" type="password" minlength="8" placeholder="Contraseña de al menos 8 caracteres" required><label class="block text-xs font-semibold">Plan de afiliación opcional<select class="mt-1 w-full p-2 rounded-xl bg-surface-container-low" name="plan" [(ngModel)]="planId"><option [ngValue]="undefined">Sin plan</option>@for(plan of plans();track plan.id){<option [ngValue]="plan.id">{{plan.epsName}} · {{plan.name}}</option>}</select></label><button class="w-full p-3 rounded-xl bg-primary text-on-primary font-bold">Crear cuenta</button></form>}
        @if(mode() === 'recovery'){<form class="space-y-3" (ngSubmit)="requestRecovery()"><input class="w-full p-3 rounded-xl bg-surface-container-low" name="recoveryEmail" [(ngModel)]="email" type="email" placeholder="Correo de la cuenta" required><button class="w-full p-3 rounded-xl bg-primary text-on-primary font-bold">Enviar instrucciones</button></form><form class="space-y-3 border-t border-outline-variant/30 pt-4" (ngSubmit)="resetPassword()"><input class="w-full p-3 rounded-xl bg-surface-container-low" name="resetToken" [(ngModel)]="resetToken" placeholder="Token de recuperación" required><input class="w-full p-3 rounded-xl bg-surface-container-low" name="newPassword" [(ngModel)]="newPassword" type="password" minlength="8" placeholder="Nueva contraseña" required><button class="w-full p-3 rounded-xl bg-secondary text-on-secondary font-bold">Cambiar contraseña</button></form>}
      </div></section></main>`
})
export class LoginPage {
  private readonly auth = inject(AuthService); private readonly api = inject(SchedulingApiService); private readonly fcv = inject(FcvDataService); private readonly router = inject(Router); private readonly platform = inject(PLATFORM_ID);
  readonly mode = signal<'login' | 'register' | 'recovery'>('login'); readonly plans = signal<PlanItem[]>([]); readonly message = signal(''); readonly error = signal(false);
  email = ''; password = ''; firstName = ''; lastName = ''; documentNumber = ''; phone = ''; planId: number | undefined; resetToken = ''; newPassword = '';
  constructor() { if (isPlatformBrowser(this.platform)) this.api.plans().subscribe({ next: x => this.plans.set(x) }); }
  login() { this.auth.login({ email: this.email, password: this.password }).subscribe({ next: r => this.go(r.user), error: () => this.show('Credenciales inválidas o servicio no disponible.', true) }); }
  register() { this.auth.register({ firstName: this.firstName, lastName: this.lastName, documentType: 'CC', documentNumber: this.documentNumber, email: this.email, phone: this.phone, password: this.password, insurancePlanId: this.planId }).subscribe({ next: r => this.go(r.user), error: e => this.show(e.status === 409 ? 'Email o documento ya registrado.' : 'No fue posible crear la cuenta.', true) }); }
  requestRecovery() { this.auth.requestPasswordRecovery(this.email).subscribe({ next: response => { if (response.developmentToken) this.resetToken = response.developmentToken; this.show('Si la cuenta existe, recibirás instrucciones para cambiar la contraseña.'); }, error: () => this.show('No fue posible procesar la solicitud.', true) }); }
  resetPassword() { this.auth.resetPassword(this.resetToken, this.newPassword).subscribe({ next: () => { this.show('Contraseña actualizada. Ya puedes iniciar sesión.'); this.mode.set('login'); this.password = ''; }, error: () => this.show('Token inválido o expirado.', true) }); }
  private go(user: { id: number; name: string; email: string; roles: ('USER' | 'PROFESSIONAL' | 'ADMIN')[] }) { this.fcv.setAuthenticatedUser(user); const role = user.roles[0]; this.router.navigateByUrl(role === 'ADMIN' ? '/administrador/solicitudes' : role === 'PROFESSIONAL' ? '/profesional/mi-agenda' : '/paciente/inicio'); }
  private show(text: string, isError = false) { this.message.set(text); this.error.set(isError); }
}
