import { ChangeDetectionStrategy, Component, PLATFORM_ID, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { isPlatformBrowser } from '@angular/common';
import { SchedulingApiService, Appointment, HistoryItem, CatalogItem, Professional, Specialty } from '../../../services/scheduling-api.service';
import { BadgeService } from '../../../services/badge.service';

@Component({selector:'app-mis-citas',changeDetection:ChangeDetectionStrategy.OnPush,imports:[FormsModule],template:`
<main class="p-6 max-w-5xl mx-auto space-y-6"><div><p class="text-xs text-outline">Portal Paciente</p><h1 class="text-2xl font-bold">Mis citas</h1></div>
<section class="rounded-3xl bg-surface-container-lowest border border-outline-variant/40 p-4 flex flex-wrap gap-3"><select class="p-2 rounded-xl bg-surface-container-low" [(ngModel)]="status" (ngModelChange)="load()" name="status"><option value="">Todos los estados</option><option value="APPROVED">Aprobadas</option><option value="REQUESTED">Pendientes</option><option value="REJECTED">Rechazadas</option><option value="CANCELLED">Canceladas</option></select><input class="p-2 rounded-xl bg-surface-container-low" type="date" [(ngModel)]="from" (ngModelChange)="load()" name="from"><input class="p-2 rounded-xl bg-surface-container-low" type="date" [(ngModel)]="to" (ngModelChange)="load()" name="to"><button class="px-4 py-2 rounded-xl bg-primary text-on-primary" (click)="load()">Filtrar</button></section>
<p>{{message()}}</p><section class="space-y-3">@for(a of items();track a.id){<article class="rounded-2xl bg-surface-container-lowest border border-outline-variant/40 p-4 flex flex-wrap items-center justify-between gap-3"><div><p class="font-bold">Cita #{{a.id}} · {{a.status}}</p><p class="text-sm text-outline">{{a.date}} · {{a.startTime}} · {{a.durationMinutes}} min</p><p class="text-sm">Sede {{locationName(a.locationId)}} · Profesional {{professionalName(a.professionalId)}} · Especialidad {{specialtyName(a.specialtyId)}}</p>@if(a.status==='REJECTED' && a.rejectionReason){<p class="text-sm text-error">Motivo de rechazo: {{a.rejectionReason}}</p>}@if(selectedId()===a.id){<div class="mt-2 border-t pt-2 text-xs space-y-1">@for(h of history();track h.occurredAt+h.status){<p><strong>{{h.status}}</strong> · {{h.source}} · {{h.occurredAt}} @if(h.reason){· {{h.reason}}}</p>}</div>}</div><div class="flex gap-2"> <button class="px-3 py-2 rounded-xl border border-primary/30" (click)="showHistory(a.id)">{{selectedId()===a.id?'Ocultar':'Historial'}}</button>@if(a.status==='APPROVED' && isFuture(a)){<button class="px-3 py-2 rounded-xl text-error border border-error/30" (click)="cancel(a.id)">Cancelar</button>}</div></article>} @empty {<p class="text-outline">No hay citas para los filtros seleccionados.</p>}</section></main>`})
export class MisCitasPage {private readonly api=inject(SchedulingApiService);private readonly badges=inject(BadgeService);private readonly platform=inject(PLATFORM_ID);readonly items=signal<Appointment[]>([]);readonly history=signal<HistoryItem[]>([]);readonly locations=signal<CatalogItem[]>([]);readonly specialties=signal<Specialty[]>([]);readonly professionals=signal<Professional[]>([]);readonly selectedId=signal<number|null>(null);readonly message=signal('');status='';from='';to='';constructor(){if(isPlatformBrowser(this.platform)){this.api.locations().subscribe({next:x=>this.locations.set(x)});this.api.specialties().subscribe({next:x=>this.specialties.set(x)});this.api.catalogProfessionals().subscribe({next:x=>this.professionals.set(x)});this.load();}}locationName(id:number){return this.locations().find(x=>x.id===id)?.name||`Sede #${id}`;}specialtyName(id:number){return this.specialties().find(x=>x.id===id)?.name||`Especialidad #${id}`;}professionalName(id:number){return this.professionals().find(x=>x.id===id)?.name||`Profesional #${id}`;}load(){this.api.mine(this.status||undefined,this.from||undefined,this.to||undefined).subscribe({next:x=>this.items.set(x),error:()=>this.message.set('No fue posible cargar tus citas.')});this.badges.refresh();}isFuture(a:Appointment){return new Date(`${a.date}T${a.startTime}`)>new Date();}showHistory(id:number){if(this.selectedId()===id){this.selectedId.set(null);return;}this.api.history(id).subscribe({next:x=>{this.history.set(x);this.selectedId.set(id);},error:()=>this.message.set('No fue posible cargar el historial.')});}cancel(id:number){this.api.cancelAppointment(id).subscribe({next:()=>{this.message.set('Cita cancelada.');this.load();},error:()=>this.message.set('La cita no se puede cancelar.')});}}
