import { ChangeDetectionStrategy, Component, PLATFORM_ID, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { isPlatformBrowser } from '@angular/common';
import { SchedulingApiService, Appointment } from '../../../services/scheduling-api.service';
import { FcvDataService } from '../../../services/fcv-data.service';

@Component({selector:'app-mis-citas',changeDetection:ChangeDetectionStrategy.OnPush,imports:[FormsModule],template:`
<main class="p-6 max-w-5xl mx-auto space-y-6"><div><p class="text-xs text-outline">Portal Paciente</p><h1 class="text-2xl font-bold">Mis citas</h1></div>
<section class="rounded-3xl bg-surface-container-lowest border border-outline-variant/40 p-4 flex flex-wrap gap-3"><select class="p-2 rounded-xl bg-surface-container-low" [(ngModel)]="status" (ngModelChange)="load()" name="status"><option value="">Todos los estados</option><option value="APPROVED">Aprobadas</option><option value="REQUESTED">Pendientes</option><option value="REJECTED">Rechazadas</option><option value="CANCELLED">Canceladas</option></select><input class="p-2 rounded-xl bg-surface-container-low" type="date" [(ngModel)]="from" (ngModelChange)="load()" name="from"><input class="p-2 rounded-xl bg-surface-container-low" type="date" [(ngModel)]="to" (ngModelChange)="load()" name="to"><button class="px-4 py-2 rounded-xl bg-primary text-on-primary" (click)="load()">Filtrar</button></section>
<p>{{message()}}</p><section class="space-y-3">@for(a of items();track a.id){<article class="rounded-2xl bg-surface-container-lowest border border-outline-variant/40 p-4 flex flex-wrap items-center justify-between gap-3"><div><p class="font-bold">Cita #{{a.id}} · {{a.status}}</p><p class="text-sm text-outline">{{a.date}} · {{a.startTime}} · {{a.durationMinutes}} min</p><p class="text-sm">Sede {{a.locationId}} · Profesional {{a.professionalId}} · Especialidad {{a.specialtyId}}</p></div>@if(a.status==='APPROVED' && isFuture(a)){<button class="px-3 py-2 rounded-xl text-error border border-error/30" (click)="cancel(a.id)">Cancelar</button>}</article>} @empty {<p class="text-outline">No hay citas para los filtros seleccionados.</p>}</section></main>`})
export class MisCitasPage {private readonly api=inject(SchedulingApiService);private readonly fcv=inject(FcvDataService);private readonly platform=inject(PLATFORM_ID);readonly items=signal<Appointment[]>([]);readonly message=signal('');status='';from='';to='';constructor(){if(isPlatformBrowser(this.platform))this.load();}load(){this.api.mine(this.status||undefined,this.from||undefined,this.to||undefined).subscribe({next:x=>this.items.set(x),error:()=>this.message.set('No fue posible cargar tus citas.')});this.api.mine().subscribe({next:x=>this.fcv.remoteAppointmentsCount.set(x.length)});}isFuture(a:Appointment){return new Date(`${a.date}T${a.startTime}`)>new Date();}cancel(id:number){this.api.cancelAppointment(id).subscribe({next:()=>{this.message.set('Cita cancelada.');this.load();},error:()=>this.message.set('La cita no se puede cancelar.')});}}
