import { ChangeDetectionStrategy, Component, PLATFORM_ID, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { isPlatformBrowser } from '@angular/common';
import { SchedulingApiService, PlanItem } from '../../../services/scheduling-api.service';

@Component({selector:'app-perfil',changeDetection:ChangeDetectionStrategy.OnPush,imports:[FormsModule],template:`
<main class="p-6 max-w-3xl mx-auto space-y-6"><div><p class="text-xs text-outline">Portal Paciente</p><h1 class="text-2xl font-bold">Mi perfil y afiliación</h1></div>
<section class="rounded-3xl bg-surface-container-lowest border border-outline-variant/40 p-5 space-y-3"><h2 class="font-bold">Datos de contacto</h2><p>{{profile()?.name}} · {{profile()?.email}}</p><input class="w-full p-3 rounded-xl bg-surface-container-low" name="phone" [(ngModel)]="phone" placeholder="Teléfono"><button class="px-4 py-2 rounded-xl bg-primary text-on-primary" (click)="savePhone()">Guardar teléfono</button></section>
<section class="rounded-3xl bg-surface-container-lowest border border-outline-variant/40 p-5 space-y-3"><h2 class="font-bold">Afiliación</h2><p class="text-sm text-outline">{{affiliation()?.epsName || 'Sin afiliación'}} {{affiliation()?.planName ? '· '+affiliation()?.planName : ''}}</p><select class="w-full p-3 rounded-xl bg-surface-container-low" name="plan" [(ngModel)]="planId"><option [ngValue]="undefined">Seleccionar plan</option>@for(plan of plans();track plan.id){<option [ngValue]="plan.id">{{plan.epsName}} · {{plan.name}}</option>}</select><button class="px-4 py-2 rounded-xl bg-primary text-on-primary" (click)="saveAffiliation()" [disabled]="!planId">Guardar afiliación</button></section><p>{{message()}}</p></main>`})
export class PerfilPage {private readonly api=inject(SchedulingApiService);private readonly platform=inject(PLATFORM_ID);readonly profile=signal<any>(null);readonly affiliation=signal<any>(null);readonly plans=signal<PlanItem[]>([]);readonly message=signal('');phone='';planId:number|undefined;constructor(){if(isPlatformBrowser(this.platform)){this.api.profile().subscribe(x=>{this.profile.set(x);this.phone=x.phone;});this.api.affiliation().subscribe(x=>this.affiliation.set(x));this.api.plans().subscribe(x=>this.plans.set(x));}}savePhone(){this.api.updatePhone(this.phone).subscribe({next:x=>{this.profile.set(x);this.message.set('Teléfono actualizado.');},error:()=>this.message.set('No fue posible actualizar el teléfono.')});}saveAffiliation(){if(this.planId)this.api.saveAffiliation(this.planId).subscribe({next:x=>{this.affiliation.set(x);this.message.set('Afiliación actualizada.');},error:()=>this.message.set('El plan no está disponible.')});}}
