import { ChangeDetectionStrategy, Component, inject, signal, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Appointment, CatalogItem, Professional, SchedulingApiService, Specialty } from '../../../services/scheduling-api.service';

@Component({ selector: 'app-admin-solicitudes', changeDetection: ChangeDetectionStrategy.OnPush, imports: [FormsModule], template: `
  <section class="space-y-6"><div class="flex justify-between"><div><p class="text-xs text-outline">Administración</p><h1 class="text-2xl font-bold">Solicitudes especializadas</h1></div><button class="px-4 py-2 rounded-xl bg-primary text-on-primary" (click)="load()">Actualizar</button></div>
  @if (message()) {<p class="text-sm" [class.text-error]="error()">{{message()}}</p>}
  <div class="rounded-3xl bg-surface-container-lowest border border-outline-variant/40 p-4 flex flex-wrap gap-2"><select class="p-2 rounded-xl" [(ngModel)]="locationId"><option [ngValue]="undefined">Todas las sedes</option>@for(l of locations();track l.id){<option [ngValue]="l.id">{{l.name}}</option>}</select><select class="p-2 rounded-xl" [(ngModel)]="professionalId"><option [ngValue]="undefined">Todos los profesionales</option>@for(p of professionals();track p.id){<option [ngValue]="p.id">{{p.name}}</option>}</select><select class="p-2 rounded-xl" [(ngModel)]="specialtyId"><option [ngValue]="undefined">Todas las especialidades</option>@for(s of specialties();track s.id){<option [ngValue]="s.id">{{s.name}}</option>}</select><input class="p-2 rounded-xl" type="date" [(ngModel)]="date"><button class="px-4 py-2 rounded-xl bg-secondary text-on-secondary" (click)="load()">Filtrar</button></div>
  <div class="rounded-3xl bg-surface-container-lowest border border-outline-variant/40 overflow-hidden"><table class="w-full text-sm"><thead><tr class="text-left bg-surface-container-low"><th class="p-3">ID</th><th>Profesional</th><th>Fecha</th><th>Duración</th><th class="p-3">Acción</th></tr></thead><tbody>@for (a of items(); track a.id) {<tr class="border-t border-outline-variant/20"><td class="p-3">#{{a.id}}</td><td>#{{a.professionalId}}</td><td>{{a.date}} {{a.startTime}}</td><td>{{a.durationMinutes}} min</td><td class="p-3 flex gap-2"><button class="px-3 py-1 rounded-lg bg-primary text-on-primary" (click)="decide(a,'APPROVE')">Aprobar</button><button class="px-3 py-1 rounded-lg bg-error text-on-error" (click)="decide(a,'REJECT')">Rechazar</button></td></tr>} @empty {<tr><td colspan="5" class="p-6 text-center text-outline">No hay solicitudes pendientes.</td></tr>}</tbody></table></div></section>` })
export class AdminSolicitudesPage {
  private readonly api = inject(SchedulingApiService); private readonly platform=inject(PLATFORM_ID); readonly items = signal<Appointment[]>([]); readonly locations=signal<CatalogItem[]>([]); readonly professionals=signal<Professional[]>([]); readonly specialties=signal<Specialty[]>([]); readonly message = signal(''); readonly error = signal(false); locationId?:number; professionalId?:number; specialtyId?:number; date='';
  constructor(){if(isPlatformBrowser(this.platform)){this.api.locations().subscribe({next:x=>this.locations.set(x)});this.api.professionals().subscribe({next:x=>this.professionals.set(x)});this.api.adminSpecialties().subscribe({next:x=>this.specialties.set(x)});this.load();}}
  load(){this.api.requested({locationId:this.locationId,professionalId:this.professionalId,specialtyId:this.specialtyId,date:this.date||undefined}).subscribe({next:x=>{this.items.set(x);this.message.set('');},error:e=>this.show(e.status===403?'Solo ADMIN puede consultar solicitudes.':'No fue posible cargar solicitudes.',true)});}
  decide(a:Appointment, decision:'APPROVE'|'REJECT'){const reason=decision==='REJECT'?prompt('Motivo de rechazo (obligatorio):')||'':'';if(decision==='REJECT'&&!reason.trim()){this.show('El motivo es obligatorio.',true);return;}this.api.decide(a.id,decision,reason).subscribe({next:()=>{this.show(decision==='APPROVE'?'Solicitud aprobada.':'Solicitud rechazada.');this.load();},error:e=>this.show(e.status===400?'Revise el motivo.':'No fue posible decidir la solicitud.',true)});}
  private show(text:string,error=false){this.message.set(text);this.error.set(error);}
}
